<template>
  <div class="admin">
    <h2 class="section-title">Admin Dashboard</h2>
    <!-- Loading "Spinner" -->
    <div v-if="isLoading" class="loadingio-spinner-bean-eater-pgmqlvey3sh">
      <div class="ldio-ugtlj07j4f">
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
    <!-- The display -->
    <div v-if="!loggedIn">
      <admin-login @login="handleLogin" />
    </div>
    <div v-else>
      <div class="admin-actions">
        <router-link to="/admin/products" class="btn btn-admin"
          >Manage Products</router-link
        >
        <router-link to="/admin/users" class="btn btn-admin"
          >Manage Users</router-link
        >
        <!-- Add other links as needed -->
      </div>
      <!-- Router view to display the nested components based on the route -->
      <router-view />
    </div>
  </div>
</template>

<script>
import AdminLogin from './AdminLogin.vue';

export default {
  components: {
    AdminLogin,
  },
  data() {
    return {
      loggedIn: false,

    };
  },
  methods: {
    handleLogin(isLoggedIn) {
      this.loggedIn = isLoggedIn;
    },
  },
};
</script>

<style scoped>
.admin {
  padding: 4rem 0;
  text-align: center;
}

.section-title {
  font-size: 2rem;
  margin-bottom: 2rem;
}

.admin-actions {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 2rem;
  margin-top: 2rem;
}

.btn-admin {
  background-color: #ff69b4;
  color: white;
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 5px;
  text-decoration: none;
  font-size: 1rem;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.btn-admin:hover {
  background-color: #ff3385;
}

/* Spinner */
@keyframes ldio-ugtlj07j4f-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-ugtlj07j4f-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-ugtlj07j4f > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-ugtlj07j4f > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #232323;
  animation: ldio-ugtlj07j4f-1 1s linear infinite;
  transform-origin: 60px 60px
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(2) {
  animation: ldio-ugtlj07j4f-2 1s linear infinite
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-ugtlj07j4f-3 {
    0% { transform: translate(190px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(70px,0); opacity: 1 }
}
.ldio-ugtlj07j4f > div:nth-child(1) {
  display: block;
}
.ldio-ugtlj07j4f > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #ff0083;
  animation: ldio-ugtlj07j4f-3 1s linear infinite
}
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-pgmqlvey3sh {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ugtlj07j4f {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ugtlj07j4f div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
