<template>
  <div class="product-details">
    <h2>Product Details</h2>
    <!-- Loading "Spinner" -->
    <div v-if="isLoading" class="loadingio-spinner-bean-eater-pgmqlvey3sh">
      <div class="ldio-ugtlj07j4f">
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
    <!-- The display -->
    <div class="product-details-card">
      <div class="product-image">
        <img :src="product.prodUrl" :alt="product.prodName" class="img-fluid" />
      </div>
      <div class="product-info">
        <h3>{{ product.prodName }}</h3>
        <p class="price">Price: R{{ product.amount }}</p>
        <p>Category: {{ product.category }}</p>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      product: {},
      isLoading: false,
    };
  },
  methods: {
    async fetchProduct(productId) {
      this.isLoading = true;
      try {
        const response = await axios.get(
          `https://node-project-fd1y.onrender.com${productId}`
        );
        this.product = response.data;
        this.isLoading = false;
      } catch (error) {
        console.error(error);
      }
    },
  },
  mounted() {
    const productId = this.$route.params.productId;
    this.fetchProduct(productId);
  },
};
</script>

<style scoped>
/* Component styles */

/* Spinner */
@keyframes ldio-ugtlj07j4f-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-ugtlj07j4f-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-ugtlj07j4f > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-ugtlj07j4f > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #232323;
  animation: ldio-ugtlj07j4f-1 1s linear infinite;
  transform-origin: 60px 60px
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(2) {
  animation: ldio-ugtlj07j4f-2 1s linear infinite
}
.ldio-ugtlj07j4f > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-ugtlj07j4f-3 {
    0% { transform: translate(190px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(70px,0); opacity: 1 }
}
.ldio-ugtlj07j4f > div:nth-child(1) {
  display: block;
}
.ldio-ugtlj07j4f > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #ff0083;
  animation: ldio-ugtlj07j4f-3 1s linear infinite
}
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-ugtlj07j4f > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-pgmqlvey3sh {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ugtlj07j4f {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ugtlj07j4f div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
